const SUPABASE_URL=window.PRIMO_SUPABASE_CONFIG?.url;
const SUPABASE_KEY=window.PRIMO_SUPABASE_CONFIG?.anonKey;
const APP_ID=window.PRIMO_SUPABASE_CONFIG?.appId||"primo_soccer_2026_kids";
const MONTHS=["JANEIRO","FEVEREIRO","MARÇO","ABRIL","MAIO","JUNHO","JULHO","AGOSTO","SETEMBRO","OUTUBRO","NOVEMBRO","DEZEMBRO"];
const CATEGORIES=[["Futbaby 2-3 Anos","cat-futbaby23"],["Futbaby 4-5 Anos","cat-futbaby45"],["Sub 6-7-8 anos","cat-sub678"],["Sub 8-9-10 anos","cat-sub8910"],["Meninas","cat-meninas"],["Sub 11-12-13-14 anos","cat-sub1114"]];
const SCHEDULE=["Segunda 09:15 • Sub 8-9-10 anos","Segunda 10:00 • Futbaby 4-5 anos","Segunda 11:00 • Futbaby 2-3 anos","Terça 10:00 • Futbaby 4-5 anos","Terça 10:45 • Sub 6-7-8 anos","Terça 15:30 • Sub 11-12-13 anos","Quarta 09:15 • Sub 8-9-10 anos","Quarta 10:00 • Futbaby 4-5 anos","Quarta 10:45 • Meninas","Quarta 15:30 • Sub 11-12-13-14","Quarta 17:30 • Futbaby 4-5 anos","Quinta 10:45 • Sub 6-7-8","Quinta 17:30 • Futbaby 2-3 anos (Capi)","Sexta 09:15 • Futbaby 4-5 anos","Sexta 17:30 • Futbaby 2-3 anos (Capi)","Sexta 18:15 • Sub 8-9-10 (Capi)","Sexta 19:10 • Sub 6-7-8 (Capi)","Sábado 09:30 • Futbaby 2-3 anos (Capi)","Sábado 10:30 • Futbaby 4-5 anos (Capi)","Sábado 11:30 • Futbaby 2-3 anos (Capi)"];
const STORAGE_KEY="primo_soccer_2026_kids_state_v1",MONTH_KEY="primo_soccer_2026_kids_month_v1";
let currentMonth=localStorage.getItem(MONTH_KEY)||"MAIO",state=loadLocal(),sb=null,saveTimer=null,currentPage="cadastro";
function defaultState(){return{students:[],months:{},currentMonth,schemaVersion:1}}
function loadLocal(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||defaultState()}catch(e){return defaultState()}}
function norm(){if(!state||typeof state!=="object")state=defaultState();if(!Array.isArray(state.students))state.students=[];if(!state.months)state.months={};state.currentMonth=currentMonth;if(!state.months[currentMonth])state.months[currentMonth]={participants:{}}}
function saveLocal(){norm();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));localStorage.setItem(MONTH_KEY,currentMonth)}
function uid(){return"KID-"+Date.now().toString(36).toUpperCase()+"-"+Math.random().toString(36).slice(2,6).toUpperCase()}
function esc(t){return String(t??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function ageFromBirth(b){if(!b)return"";const d=new Date(b+"T00:00:00"),now=new Date();let a=now.getFullYear()-d.getFullYear();const m=now.getMonth()-d.getMonth();if(m<0||(m===0&&now.getDate()<d.getDate()))a--;return a}
function initials(n){return String(n||"A").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"A"}
function studentById(id){return state.students.find(s=>s.id===id)}
function monthObj(m=currentMonth){norm();if(!state.months[m])state.months[m]={participants:{}};return state.months[m]}
function participant(id,create=true){const mo=monthObj();if(!mo.participants[id]&&create)mo.participants[id]={studentId:id,schedules:[],weeks:Array.from({length:5},()=>({}))};return mo.participants[id]||null}
function emptyScore(){return{pd:0,pe:0,uniforme:0,fruta:0,comportamento:0}}
function getScore(id,w,sch){const p=participant(id);if(!p.weeks[w])p.weeks[w]={};if(!p.weeks[w][sch])p.weeks[w][sch]=emptyScore();return p.weeks[w][sch]}
function scoreTotal(sc){return(+sc.pd||0)+(+sc.pe||0)+(+sc.uniforme||0)+(+sc.fruta||0)+(+sc.comportamento||0)}
function totalStudent(id,m=currentMonth){const p=monthObj(m).participants[id];if(!p)return 0;return(p.weeks||[]).reduce((a,w)=>a+Object.values(w||{}).reduce((b,sc)=>b+scoreTotal(sc),0),0)}
function activeStudents(m=currentMonth){const ids=new Set(Object.entries(monthObj(m).participants||{}).filter(([id,p])=>p.schedules&&p.schedules.length).map(([id])=>id));return state.students.filter(s=>s.active!==false&&ids.has(s.id))}
function ranked(cat=null){return activeStudents().filter(s=>!cat||s.category===cat).map(s=>({...s,total:totalStudent(s.id)})).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name))}
function avatarHtml(s){return s.photo?`<span class="avatar"><img src="${s.photo}"></span>`:`<span class="avatar">${initials(s.name)}</span>`}
function photoPickerHtml(s){return`<label class="avatarInputLabel">${s.photo?`<img src="${s.photo}">`:initials(s.name)}<input class="photoInput" type="file" accept="image/*" onchange="loadPhoto(event,'${s.id}')"></label>`}
function loadPhoto(e,id){const file=e.target.files&&e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=420;let w=img.width,h=img.height;if(w>h&&w>max){h=Math.round(h*max/w);w=max}else if(h>=w&&h>max){w=Math.round(w*max/h);h=max}const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);const s=studentById(id);if(s){s.photo=c.toDataURL("image/jpeg",.82);scheduleSave();renderAll()}};img.src=r.result};r.readAsDataURL(file)}
function setSync(msg,type="warn"){const el=document.getElementById("syncStatus");el.textContent=msg;el.style.color=type==="ok"?"#8ff0b3":type==="error"?"#ff8b8b":"#ffe082"}
function scheduleSave(){saveLocal();clearTimeout(saveTimer);saveTimer=setTimeout(saveCloud,700)}
function showPage(page){currentPage=page;["cadastro","agenda","pontos","categorias","ranking","config"].forEach(p=>{document.getElementById("page-"+p).classList.toggle("hidden",p!==page);document.getElementById("tab-"+p).classList.toggle("active",p===page)});renderAll()}
function renderAll(){norm();renderMonth();renderSelectors();renderStudents();renderAgenda();renderScore();renderCategoryRankings();renderRanking()}
function renderMonth(){const sel=document.getElementById("monthSelect");if(!sel.dataset.ready){sel.innerHTML=MONTHS.map(m=>`<option value="${m}">${m}</option>`).join("");sel.dataset.ready="1";sel.onchange=()=>{currentMonth=sel.value;if(!state.months[currentMonth])state.months[currentMonth]={participants:{}};scheduleSave();renderAll()}}sel.value=currentMonth;document.getElementById("heroMonth").textContent=currentMonth}
function renderSelectors(){document.getElementById("studentCategory").innerHTML=CATEGORIES.map(c=>`<option value="${c[0]}">${c[0]}</option>`).join("");document.getElementById("studentPicker").innerHTML=state.students.filter(s=>s.active!==false).map(s=>`<option value="${s.id}">${esc(s.name)} • ${esc(s.category)}</option>`).join("")||`<option value="">Cadastre alunos</option>`;document.getElementById("schedulePicker").innerHTML=SCHEDULE.map(s=>`<option value="${s}">${s}</option>`).join("");document.getElementById("scoreSchedule").innerHTML=SCHEDULE.map(s=>`<option value="${s}">${s}</option>`).join("");document.getElementById("scoreWeek").innerHTML=[0,1,2,3,4].map(i=>`<option value="${i}">Semana ${i+1}</option>`).join("");renderCopyMonthPicker()}
function addStudent(){const name=document.getElementById("studentName").value.trim(),birth=document.getElementById("studentBirth").value,category=document.getElementById("studentCategory").value;if(!name)return alert("Digite o nome do aluno.");state.students.push({id:uid(),name,birth,category,active:true,photo:"",createdAt:new Date().toISOString()});document.getElementById("studentName").value="";document.getElementById("studentBirth").value="";scheduleSave();renderAll();alert("Aluno cadastrado!")}
function renderStudents(){document.getElementById("studentsTable").innerHTML=state.students.filter(s=>s.active!==false).map((s,i)=>`<tr><td>${i+1}</td><td>${photoPickerHtml(s)}</td><td><input value="${esc(s.name)}" oninput="editStudent('${s.id}','name',this.value)"></td><td><input type="date" value="${s.birth||""}" oninput="editStudent('${s.id}','birth',this.value)"></td><td>${ageFromBirth(s.birth)} anos</td><td><select onchange="editStudent('${s.id}','category',this.value)">${CATEGORIES.map(c=>`<option value="${c[0]}" ${s.category===c[0]?"selected":""}>${c[0]}</option>`).join("")}</select></td><td><button class="danger" onclick="deleteStudent('${s.id}')">Excluir</button></td></tr>`).join("")||`<tr><td colspan="7">Nenhum aluno cadastrado.</td></tr>`}
function editStudent(id,field,value){const s=studentById(id);if(s){s[field]=value;scheduleSave()}}
function deleteStudent(id){if(!confirm("Excluir aluno e todos os pontos dele?"))return;state.students=state.students.filter(s=>s.id!==id);Object.values(state.months||{}).forEach(m=>{if(m.participants)delete m.participants[id]});scheduleSave();renderAll()}
function addToSchedule(){const id=document.getElementById("studentPicker").value,sch=document.getElementById("schedulePicker").value;if(!id||!sch)return;const studentsInSlot=activeStudents().filter(s=>(participant(s.id,false)?.schedules||[]).includes(sch));if(studentsInSlot.length>=6)return alert("Esse horário já está com 6 vagas preenchidas.");const p=participant(id);if(!p.schedules.includes(sch))p.schedules.push(sch);scheduleSave();renderAll()}
function renderAgenda(){document.getElementById("agendaGrid").innerHTML=SCHEDULE.map(sch=>{const list=activeStudents().filter(s=>(participant(s.id,false)?.schedules||[]).includes(sch));return`<div class="slotCard"><div class="slotTitle"><span>${sch}</span><span class="badge">${list.length}/6</span></div>${list.map(s=>`<div class="item"><span>${esc(s.name)}</span><button class="danger" onclick="removeFromSchedule('${s.id}','${sch}')">Remover</button></div>`).join("")||"<p>Nenhum aluno.</p>"}</div>`}).join("")}
function removeFromSchedule(id,sch){const p=participant(id,false);if(p){p.schedules=p.schedules.filter(x=>x!==sch);scheduleSave();renderAll()}}
function renderScore(){const sch=document.getElementById("scoreSchedule").value||SCHEDULE[0],week=+document.getElementById("scoreWeek").value||0;document.getElementById("scoreTitle").textContent=`${currentMonth} • Semana ${week+1} • ${sch}`;const list=activeStudents().filter(s=>(participant(s.id,false)?.schedules||[]).includes(sch));document.getElementById("scoreTable").innerHTML=list.map((s,i)=>{const score=getScore(s.id,week,sch);return`<tr><td>${i+1}</td><td class="sticky"><div class="playerCell">${avatarHtml(s)}<strong>${esc(s.name)}</strong></div></td><td><input class="scoreInput" type="number" value="${score.pd}" oninput="setScore('${s.id}',${week},'${sch}','pd',this.value)"></td><td><input class="scoreInput" type="number" value="${score.pe}" oninput="setScore('${s.id}',${week},'${sch}','pe',this.value)"></td>${["uniforme","fruta","comportamento"].map(field=>`<td><select class="bonusSelect" onchange="setScore('${s.id}',${week},'${sch}','${field}',this.value)"><option value="0" ${score[field]==0?"selected":""}>0</option><option value="5" ${score[field]==5?"selected":""}>5</option></select></td>`).join("")}<td><strong>${scoreTotal(score)}</strong></td></tr>`}).join("")||`<tr><td colspan="8">Nenhum aluno neste horário.</td></tr>`}
function setScore(id,week,sch,field,value){getScore(id,week,sch)[field]=+value||0;scheduleSave();renderCategoryRankings();renderRanking()}
function clearTrainingScore(){const sch=document.getElementById("scoreSchedule").value,week=+document.getElementById("scoreWeek").value;if(!confirm("Limpar pontuação deste treino?"))return;activeStudents().forEach(s=>{const p=participant(s.id,false);if(p?.weeks?.[week]?.[sch])p.weeks[week][sch]=emptyScore()});scheduleSave();renderAll()}
function rankRow(s,i){return`<div class="rankRow"><div class="rankLeft"><span>${i===0?"🥇":i===1?"🥈":i===2?"🥉":"⚽"}</span>${avatarHtml(s)}<span>${i+1}º - ${esc(s.name)}</span></div><strong>${s.total} pts</strong></div>`}
function renderRanking(){document.getElementById("rankingGeneral").innerHTML=ranked().map(rankRow).join("")||"<p>Nenhum aluno ativo no mês.</p>"}
function renderCategoryRankings(){document.getElementById("categoryRankings").innerHTML=CATEGORIES.map(c=>{const list=ranked(c[0]);return`<div class="catCard ${c[1]}"><h2>${c[0]}</h2>${list.map(rankRow).join("")||"<p>Nenhum aluno ativo.</p>"}</div>`}).join("")}
function renderCopyMonthPicker(){const picker=document.getElementById("copyMonthPicker");const available=MONTHS.filter(m=>m!==currentMonth&&Object.values(state.months?.[m]?.participants||{}).some(p=>p.schedules&&p.schedules.length));picker.innerHTML=available.map(m=>`<option value="${m}">${m}</option>`).join("")||`<option value="">Nenhum mês com agenda</option>`}
function copyAgendaFromMonth(){const source=document.getElementById("copyMonthPicker").value;if(!source)return alert("Nenhum mês com agenda para copiar.");const sourceMo=monthObj(source),targetMo=monthObj(currentMonth);const entries=Object.entries(sourceMo.participants||{}).filter(([id,p])=>p.schedules&&p.schedules.length);if(!entries.length)return alert("Esse mês não possui agenda.");if(!confirm(`Copiar ${entries.length} aluno(s) e horários de ${source} para ${currentMonth} com pontuação zerada?`))return;entries.forEach(([id,p])=>{targetMo.participants[id]={studentId:id,schedules:[...p.schedules],weeks:Array.from({length:5},()=>({}))}});scheduleSave();renderAll();alert("Agenda copiada com pontuação zerada.")}
function clearMonthAgenda(){if(!confirm("Limpar agenda do mês atual?"))return;Object.values(monthObj().participants||{}).forEach(p=>p.schedules=[]);scheduleSave();renderAll()}
async function initCloud(){try{setSync("Conectando ao banco online...");if(!window.supabase)throw new Error("Biblioteca Supabase não carregou");sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const{data,error}=await sb.from("primo_app_state").select("data").eq("app_id",APP_ID).maybeSingle();if(error)throw error;if(data&&data.data&&Object.keys(data.data).length){const keepMonth=currentMonth;state=data.data;currentMonth=keepMonth;saveLocal()}else{await saveCloud()}setSync("Dados online conectados.","ok");renderAll()}catch(e){console.error(e);setSync("Erro online: confirme SQL e config.","error")}}
async function saveCloud(){if(!sb){if(!window.supabase)return;sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY)}try{norm();const{error}=await sb.from("primo_app_state").upsert({app_id:APP_ID,data:state,updated_at:new Date().toISOString()},{onConflict:"app_id"});if(error)throw error;setSync("Dados salvos online.","ok")}catch(e){console.error(e);setSync("Erro ao salvar online.","error")}}
async function syncNow(){await saveCloud();alert("Sincronizado")}
async function loadCloud(){await initCloud()}
renderAll();showPage("cadastro");initCloud();
